put:
  summary: Update account configuration
  description: This endpoint changes the name associated with an account
  tags:
    - Accounts
  operationId: updateAccountConfig
  parameters:
    - in: path
      required: true
      name: ican
      schema:
        type: string
        description: The unique id for the account
        example: "12345"
  requestBody:
    required: true
    description: The name the account name should be changed to
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/AccountConfiguration'

  responses:
    "204":
      description: The account was updated.
