title: apiApplication
type: object
properties:
  applicationId:
    type: integer
    format: int64
    description: The ID of the API Application
    example: 45345
  ican:
    type: integer
    format: int64
    description: The ICAN of one of your Fire accounts. Restrict this API Application to a certan account.
  enabled:
    type: boolean
    example: true
    description: Whether or not this API Application can be used
  expiry:
    type: string
    format: date-time
    example: "2019-08-22T07:48:56.460Z"
    description: The date that this API Application can no longer be used.
  numberOfPaymentApprovalsRequired:
    type: integer
    description: Number of approvals required to process a payment in a batch
    example: 1
  numberOfPayeeApprovalsRequired:
    type: integer
    description: Number of approvals required to create a payee in a batch
    example: 1
  clientId:
    type: string
    description: The Client ID of the new API Application
    example: "4ADFB67A-0F5B-4A9A-9D74-34437250045C"
  clientKey:
    type: string
    description: The Client Key of the new API Application
    example: "4ADFB67A-0F5B-4A9A-9D74-34437250045C"
  refreshToken:
    type: string
    description: The Refresh Token of the new API Application
    example: "4ADFB67A-0F5B-4A9A-9D74-34437250045C"
