title: apiApplication
type: object
properties:
  applicationId:
    type: integer
    format: int64
    description: This is the ID number of the API application
    example: 2404
  name:
    type: string
    description: This is the name given to the API application by the fire.com user
    example: "Account Information Test"
  ican:
    type: integer
    format: int64
    description: The ICAN of one of your Fire accounts. Restrict this API Application to a certan account.
  clientId:
    type: string
    description: This is the ID of client associated with the application
    example: "G0919C06D23D-362A-H5D3-E76D8687D6AE"
  refreshToken:
    type: string
    description: This is the refresh token associated with the application
    example: "9C332CF3-1687-4548-8E0E-55E4F0599800"
  clientKey:
    type: string
    description: The Client Key of the new API Application
    example: "4ADFB67A-0F5B-4A9A-9D74-34437250045C"
  enabled:
    type: boolean
    description: This is whether or not the application is enabled for usage
  numberOfApprovalsRequired:
    type: integer
    format: int64
    description: This is the number of approvals required for any application actions
    example: 1
  numberOfPaymentApprovalsRequired:
    type: integer
    format: int64
    description: This is number of approvals required for any payment batches
    example: 1
  numberOfPayeeApprovalsRequired:
    type: integer
    format: int64
    description: This is the number of approvals required for Payees
    example: 1
  expiry:
    type: string
    format: date-time
    example: "2019-08-22T07:48:56.460Z"
    description: The date that this API Application can no longer be used.



