title: newApiApplication
type: object
properties:
  applicationName:
    type: string
    description: A name for the API Application to help you identify it
    example: Batch Processing API
  numberOfPaymentApprovalsRequired:
    type: integer
    description: Number of approvals required to process a payment in a batch
    example: 1
  numberOfPayeeApprovalsRequired:
    type: integer
    description: Number of approvals required to create a payee in a batch
    example: 1
  isPayeeCheckEnabled:
    type: boolean
    description: This is whether or not Verfication of Payee checks are required for SEPA payments before a batch can be submitted.
  permissions:
    type: array
    items:
      type: string
    description: The list of permissions required
    example: [ "PERM_BUSINESS_POST_PAYMENT_REQUEST","PERM_BUSINESS_GET_ASPSPS" ]
