openapi: '3.0.3'
info:
  title: Fire Financial Services Business API
  description: >
    The fire.com API allows you to deeply integrate Business Account features into your application or back-office systems.
  version: '1.0'
  contact: 
    name: Fire API
    url: https://docs.fire.com
    email: api@fire.com
servers:
  - url: https://api.fire.com/business
    description: Production Server
paths:
  /v1/apps/accesstokens:
    $ref: ./paths/v1.0/apps/accesstokens.yaml
    
  /v1/accounts:
    $ref: ./paths/v1.0/accounts/accounts.yaml
    
  /v1/accounts/{ican}:
    $ref: ./paths/v1.0/accounts/accounts-by-ican.yaml

  /v1/accounts/{ican}/transactions:
    $ref: ./paths/v1.0/accounts/transactions-by-account-v1.yaml 

  /v3/accounts/{ican}/transactions:
    $ref: ./paths/v1.0/accounts/transactions-by-account-v3.yaml 

  /v1/accounts/{ican}/transactions/filter:
    $ref: ./paths/v1.0/accounts/transactions-by-account-filtered.yaml 

  /v1/cards:
    $ref: ./paths/v1.0/cards/cards.yaml

  /v1/cards/{cardId}/transactions:
    $ref: ./paths/v1.0/cards/card-transactions.yaml

  /v1/cards/{cardId}/block:
    $ref: ./paths/v1.0/cards/card-block.yaml

  /v1/cards/{cardId}/unblock:
    $ref: ./paths/v1.0/cards/card-unblock.yaml
    
  /v1/paymentrequests:
    $ref: ./paths/v1.0/paymentrequests/paymentrequests.yaml

  /v1/aspsps:
    $ref: ./paths/v1.0/aspsps/aspsps.yaml

# This endpoint is for Bankpay only. 
#  /payments/{paymentUuid}/bankpayrefund:
#    $ref: ./paths/v1.0/payments/refund-payment-by-paymentuuid.yaml

  /v1/payments/{paymentUuid}:
    $ref: ./paths/v1.0/payments/payments-by-paymentuuid.yaml

  /v1/users:
    $ref: ./paths/v1.0/users/users.yaml

  /v1/user/{userId}:
    $ref: ./paths/v1.0/users/user-by-userid.yaml

  /v1/apps:
    $ref: ./paths/v1.0/apps/apps.yaml

  /v1/payees:
    $ref: ./paths/v1.0/payees/payees.yaml

  /v1/directdebits:
    $ref: ./paths/v1.0/directdebits/directdebits.yaml

  /v1/directdebits/{directDebitUuid}:
    $ref: ./paths/v1.0/directdebits/directdebit-by-directdebituuid.yaml

  /v1/directdebits/{directDebitUuid}/reject:
    $ref: ./paths/v1.0/directdebits/reject-directdebit-by-uuid.yaml

  /v1/mandates:
    $ref: ./paths/v1.0/mandates/mandates.yaml

  /v1/mandates/{mandateUuid}:
    $ref: ./paths/v1.0/mandates/mandate-by-uuid.yaml

  /v1/mandates/{mandateUuid}/cancel:
    $ref: ./paths/v1.0/mandates/cancel-mandate-by-uuid.yaml

  /v1/mandates/{mandateUuid}/activate:
    $ref: ./paths/v1.0/mandates/activate-mandate-by-uuid.yaml

  /v1/batches:
    $ref: ./paths/v1.0/batches/batches.yaml

  /v1/batches/{batchUuid}/internaltransfers:
    $ref: ./paths/v1.0/batches/internaltransfers.yaml

  /v1/batches/{batchUuid}/banktransfers:
    $ref: ./paths/v1.0/batches/banktransfers.yaml

  /v2/batches/{batchUuid}/internationaltransfers:
    $ref: ./paths/v1.0/batches/internationaltransfers.yaml

  /v1/batches/{batchUuid}/internaltransfers/{itemUuid}:
    $ref: ./paths/v1.0/batches/internaltransfer-by-itemuuid.yaml

  /v1/batches/{batchUuid}/banktransfers/{itemUuid}:
    $ref: ./paths/v1.0/batches/banktransfer-by-itemuuid.yaml

  /v2/batches/{batchUuid}/internationaltransfers/{itemUuid}:
    $ref: ./paths/v1.0/batches/internationaltransfer-by-itemuuid.yaml

  /v1/batches/{batchUuid}:
    $ref: ./paths/v1.0/batches/batch-by-batchuuid.yaml

  /v1/batches/{batchUuid}/approvals:
    $ref: ./paths/v1.0/batches/approvers-for-batch.yaml

# webhooks:
#   events:
#     $ref: ./webhooks/events.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: API Access Token
  responses:
    UnauthorisedError:
      description: Access Token is Invalid or missing
  parameters:
    orderParam:
      name: order
      in: query
      required: false
      description: Either `ASC` or `DESC`
      schema:
        enum:
            - ASC
            - DESC
    orderByParam:
      name: orderBy
      in: query
      required: false
      description: Currently defaults to `DATE` No other options at this time.
      schema:
        enum:
            - DATE
    limitParam:
      name: limit
      in: query
      required: false
      description: The number of records to return. Defaults to 10 - max is 200.
      schema:
        type: integer
        default: 10
        maximum: 200
    offsetParam:
      name: offset
      in: query
      required: false
      description: The page offset. Defaults to 0. This is the record number that the returned list will start at. E.g. `offset = 40` and `limit = 20` will return records 40 to 59.
      schema:
        type: integer
        default: 0
security:
  - bearerAuth: []
tags:
  - name: Authentication
    description: Access to the API is by Bearer Access Tokens. 
  - name: Accounts
    description: fire.com Accounts are the equivalent of a bank account from bank.
  - name: Open Banking
    description: Fire Open Payments is a feature of the fire.com business account that leverages Open Banking to allow your customers to pay you via bank transfer and to reconcile those payments as they are received into your fire.com GBP or EUR account.
  - name: API
    description: Manage your API Applications and Webhooks
  - name: Transactions
    description: There are many types of transactions. They are all represented by the same JSON object with a different txnType.
  - name: Direct Debits
    description: The fire.com api allows businesses to automate direct debit payment actions on their fire.com business accounts.
  - name: Payment Batches
    description: The fire.com API allows businesses to automate payments between their accounts or to third parties across the UK and Europe.
  - name: Payees
    description: List the beneficiaries associated with the account. 
  - name: Cards
    description: View and manage the cards linked to your accounts. 
  - name: Users
    description: View the users of your fire.com account. 
   
