name: Sync OAS to ReadMe (prod)

on:
  push:
    branches:
      - v2.0

jobs:
  sync-openapi-to-readme-prod:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.x'
      - run: npm install -g json-refs
      - run: json-refs resolve --yaml -f --filter relative ./src/fire-business-api-v1.yaml > ./fire-business-api-v1.yaml
      
      - name: Test commands
        run: |
            grep -n yaml ./fire-business-api-v1.yaml 

      - name: Upload OpenAPI spec to ReadMe
        uses: readmeio/rdme@v10
        with:
          rdme: openapi upload ./fire-business-api-v1.yaml --key=${{ secrets.README_API_KEY }} --branch=v2.0
