on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy API doc
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Deploy
      id: deploy
      uses: bump-sh/github-action@master
      with:
        doc: ${{ secrets.DOC_ID }}
        token: ${{ secrets.DOC_TOKEN }}
        file: dist/fire-business-api-v1.yaml
