name: Sync OAS to ReadMe (prod)
on:
  push:
    branches:
      - master
      - main
jobs:
  sync-openapi-to-readme-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: readmeio/rdme@8.6.2
        with:
          rdme: openapi ./fire-business-api-v1.yaml --workingDirectory=src --key=${{ secrets.README_API_KEY }} --id=6136360239a7a64894f1c269
# 6136360239a7a64894f1c269 is the _id for the v1.0 version. Got this from the ReadMe https://dash.readme.com/project/fire-business-api/v1.0/reference

  sync-guide-docs-to-readme-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: readmeio/rdme@8.6.2
        with:
          rdme: docs guides --key=${{ secrets.README_API_KEY }} --version=v1.0
      